/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.net.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import pong.Pong;

/**
 *
 * @author Animesh
 */
public class ServerGUI extends javax.swing.JFrame  {

    ServerSocket serverSocket;
    int port;
    Boolean isConnected = false;
    String username;
    Socket clientSocket;
    OutputStream ostream;
    PrintWriter writer;
    
    public class PongServer implements Runnable{
        
        public void run(){
            try {
                    PongMulti p1 = new PongMulti();
            } catch (InterruptedException ex) {
                Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public class ClientHandler implements Runnable{
    BufferedReader reader;
    PrintWriter client;
    
    public ClientHandler(Socket socket,PrintWriter user){
        client = user;
        try{
            
            clientSocket = socket;
            InputStreamReader isReader = new InputStreamReader(clientSocket.getInputStream());
            reader = new BufferedReader(isReader);
        }catch(IOException ex){
            System.out.println(ex);
        }
    }
    
        @Override
        public void run() {
            String message;
          try{
              while((message = reader.readLine()) != null){
                  jTextArea_ChatWindow.append(message + "\n");
              }
          }catch(IOException ex){
              System.out.println(ex);
            }
          }
        }
        

    /**
     * Creates new form ChatGUI
     * @throws java.io.IOException
     */
    
    
    
    public void connect() throws IOException{
        
        serverSocket = new ServerSocket(port);
        clientSocket = serverSocket.accept();
        writer = new PrintWriter(clientSocket.getOutputStream(), true);
        jTextArea_ChatWindow.append("Friend connected\n");
        Thread listener = new Thread(new ClientHandler(clientSocket, writer));
        listener.start();
    }
    
    public ServerGUI() {
        
        initComponents();
    }

    //public class IncomingReader implements Runnable{}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Username = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jButton_Connect = new javax.swing.JButton();
        jButton_Disconnect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ChatWindow = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Text_Input = new javax.swing.JTextArea();
        jButton_Send = new javax.swing.JButton();
        Port = new javax.swing.JLabel();
        jTextField_PortNumber = new javax.swing.JTextField();
        jButton_PingPong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        jLabel_Username.setText("Username");

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jButton_Connect.setText("Start Connection");
        jButton_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConnectActionPerformed(evt);
            }
        });

        jButton_Disconnect.setText("Disconnect");
        jButton_Disconnect.setEnabled(false);
        jButton_Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DisconnectActionPerformed(evt);
            }
        });

        jTextArea_ChatWindow.setEditable(false);
        jTextArea_ChatWindow.setColumns(20);
        jTextArea_ChatWindow.setLineWrap(true);
        jTextArea_ChatWindow.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ChatWindow);

        jTextArea_Text_Input.setColumns(20);
        jTextArea_Text_Input.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Text_Input);

        jButton_Send.setText("Send Message");
        jButton_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendActionPerformed(evt);
            }
        });

        Port.setText("Port");

        jButton_PingPong.setText("Play Ping Pong");
        jButton_PingPong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PingPongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Port)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_PingPong)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Connect)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Disconnect)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Username)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Connect)
                    .addComponent(jButton_Disconnect)
                    .addComponent(Port)
                    .addComponent(jTextField_PortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton_PingPong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jButton_DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DisconnectActionPerformed
        // TODO add your handling code here:
        try {
            writer.println(username + " has disconnected");
            clientSocket.close();
            serverSocket.close();
            isConnected = false;
            jButton_Connect.setEnabled(true);
            jButton_Disconnect.setEnabled(false);
            
            }catch (IOException ex) {
            
        }
    }//GEN-LAST:event_jButton_DisconnectActionPerformed

    private void jButton_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConnectActionPerformed
        // TODO add your handling code here:
        if(isConnected == false){
            if("".equals(jTextField_Username.getText()) || "".equals(jTextField_PortNumber.getText()))
            {
                System.out.println("Please enter required parameters");
            }else{
                username = jTextField_Username.getText();
                port = Integer.parseInt(jTextField_PortNumber.getText());
                try {
                    connect();
                    jButton_Connect.setEnabled(false);
                    jButton_Disconnect.setEnabled(true);
                } catch (IOException ex) {
                   System.out.println(ex);
                }   
            }
        }
    }//GEN-LAST:event_jButton_ConnectActionPerformed

    private void jButton_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendActionPerformed
        // TODO add your handling code here:
        if("".equals(jTextArea_Text_Input.getText())){
            // do nothing
        }else{
           try{
                writer.println(username + ":" + jTextArea_Text_Input.getText());
                writer.flush();
                jTextArea_ChatWindow.append(username + ":" + jTextArea_Text_Input.getText() + "\n");
                jTextArea_Text_Input.setText("");
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton_SendActionPerformed

    private void jButton_PingPongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PingPongActionPerformed
        // TODO add your handling code here:
        Thread listener = new Thread(new PongServer());
        listener.start();
    }//GEN-LAST:event_jButton_PingPongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Port;
    private javax.swing.JButton jButton_Connect;
    private javax.swing.JButton jButton_Disconnect;
    private javax.swing.JButton jButton_PingPong;
    private javax.swing.JButton jButton_Send;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_ChatWindow;
    private javax.swing.JTextArea jTextArea_Text_Input;
    private javax.swing.JTextField jTextField_PortNumber;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
